
@startuml UseCase
!theme plain

left to right direction
skinparam packageStyle rectangle

actor User

rectangle "Galaxy Weather System" {
    usecase "Enter Location" as UC1
    usecase "Upload JSON Data" as UC2
    usecase "Request Forecast" as UC3
    usecase "View Forecast Result" as UC4
    usecase "View Forecast History" as UC5
}

User --> UC1
User --> UC2
User --> UC3
User --> UC4
User --> UC5

UC3 ..> UC1 : <<include>>
UC3 ..> UC4 : <<include>>

@enduml
